name: PodcastTransfer
options:
  deploymentTarget:
    macOS: "14.0"
targets:
  PodcastTransfer:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: ../Sources/PodcastTransferApp
      - path: Resources
        buildPhase: resources
    dependencies:
      - package: PodcastTransfer
        product: PodcastTransferUI
      - package: PodcastTransfer
        product: PodcastTransferFeature
      - package: PodcastTransfer
        product: PodcastTransferCore
    settings:
      PRODUCT_NAME: "Podcast Transfer"
      PRODUCT_BUNDLE_IDENTIFIER: us.atlasapps.podcasttransfer
      SWIFT_VERSION: 6.0
      GENERATE_INFOPLIST_FILE: YES
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      INFOPLIST_KEY_CFBundleIconName: AppIcon
      INFOPLIST_KEY_CFBundleDisplayName: "Podcast Transfer"
      INFOPLIST_KEY_CFBundleName: "Podcast Transfer"
      INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: 3Z68NFJBHS
packages:
  PodcastTransfer:
    path: ..
schemes:
  PodcastTransfer:
    build:
      targets:
        PodcastTransfer: all
